<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-16T18:39:17 IST" name="Suite" finished-at="2024-01-16T18:40:06 IST" duration-ms="49171">
    <groups>
      <group name="Functional">
        <method signature="EventTestCase.verifyUpdateByRoomEvent()[pri:0, instance:tests.EventTestCase@435ce306]" name="verifyUpdateByRoomEvent" class="tests.EventTestCase"/>
      </group> <!-- Functional -->
      <group name="Regression">
        <method signature="EventTestCase.verifyUpdateByRoomEvent()[pri:0, instance:tests.EventTestCase@435ce306]" name="verifyUpdateByRoomEvent" class="tests.EventTestCase"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2024-01-16T18:39:17 IST" name="Test" finished-at="2024-01-16T18:40:06 IST" duration-ms="49171">
      <class name="tests.EventTestCase">
        <test-method is-config="true" signature="configReport()[pri:0, instance:tests.EventTestCase@435ce306]" started-at="2024-01-16T18:39:17 IST" name="configReport" finished-at="2024-01-16T18:39:17 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configReport -->
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.EventTestCase@435ce306]" started-at="2024-01-16T18:39:17 IST" name="setup" finished-at="2024-01-16T18:39:28 IST" duration-ms="10358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyUpdateByRoomEvent()[pri:0, instance:tests.EventTestCase@435ce306]" started-at="2024-01-16T18:39:28 IST" name="verifyUpdateByRoomEvent" description="Verify Updating Room Event and checking on Add Appointment room is disabled for update event time slot and room is available on previous time slot." finished-at="2024-01-16T18:40:06 IST" duration-ms="38139" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at pageActions.doctorDashboard.EventPageActions.checkDisableEnableOfOperatoryOnAddAppointment(EventPageActions.java:798)
at pageActions.doctorDashboard.EventPageActions.checkRoomIsSelectableOnAddAppt(EventPageActions.java:864)
at tests.EventTestCase.verifyUpdateByRoomEvent(EventTestCase.java:877)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUpdateByRoomEvent -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.EventTestCase@435ce306]" started-at="2024-01-16T18:40:06 IST" name="tearDown" finished-at="2024-01-16T18:40:06 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.EventTestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
